name: "Deploy to gh-page"
description: "The action build and push the output to gh-page branch"
inputs:
  source:
    description: "Where the project located"
    required: false
    default: ./
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source }}