on: [push]

jobs:
  test-build:
    runs-on: ubuntu-latest
    name: Testing build pelican website
    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build the test project
        id: build
        uses: ./
        with:
          source: test_projects/hello
      - name: Verify output
        run: | 
          ls
          pwd
          ls ./test_projects/hello/output
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-without-markdown
          path: |
            ./test_projects/hello/output